### ISSUE TITLE
API endpoint: GET portfolio list by user id

### ISSUE THREAD

**Issue by DavidLHW** [is442oop/portfolio-analyzer-backend#19]

**Comment by TimothyNgoi98** [comment]
Yo, I did this up already in a previous PR #13 
https://github.com/is442oop/portfolio-analyzer-backend/blob/1132f81170f45e3c3a37d686625ccdce72171129/src/main/java/com/backend/controller/UserController.java#L96-L107

**Comment by DavidLHW** [comment]
closing as duplicate!
